# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: atc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'atc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tatc.proto\x12\x03\x61tc\"X\n\rAirwayRequest\x12\x13\n\x0b\x61ircraft_id\x18\x01 \x01(\t\x12\x10\n\x08\x61ltitude\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\x05\x12\x0e\n\x06\x61irway\x18\x04 \x01(\t\"F\n\rRunwayRequest\x12\x13\n\x0b\x61ircraft_id\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\x12\x0e\n\x06runway\x18\x03 \x01(\t\"4\n\x0bGateRequest\x12\x13\n\x0b\x61ircraft_id\x18\x01 \x01(\t\x12\x10\n\x08\x64uration\x18\x02 \x01(\x05\"\\\n\x15\x41ssignAircraftRequest\x12\x13\n\x0b\x61ircraft_id\x18\x01 \x01(\t\x12\x0e\n\x06runway\x18\x02 \x01(\t\x12\x0c\n\x04gate\x18\x03 \x01(\t\x12\x10\n\x08\x61irspace\x18\x04 \x01(\t\"\x07\n\x05\x45mpty\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t2\x85\x03\n\x11\x41irTrafficControl\x12\x33\n\x0eIncomingAirway\x12\x12.atc.AirwayRequest\x1a\r.atc.Response\x12\x34\n\x0f\x44\x65partingAirway\x12\x12.atc.AirwayRequest\x1a\r.atc.Response\x12\x32\n\rLandingRunway\x12\x12.atc.RunwayRequest\x1a\r.atc.Response\x12\x34\n\x0f\x44\x65partingRunway\x12\x12.atc.RunwayRequest\x1a\r.atc.Response\x12\x31\n\x0eGateAssignment\x12\x10.atc.GateRequest\x1a\r.atc.Response\x12;\n\x0e\x41ssignAircraft\x12\x1a.atc.AssignAircraftRequest\x1a\r.atc.Response\x12+\n\x0eReleaseRunways\x12\n.atc.Empty\x1a\r.atc.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'atc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRWAYREQUEST']._serialized_start=18
  _globals['_AIRWAYREQUEST']._serialized_end=106
  _globals['_RUNWAYREQUEST']._serialized_start=108
  _globals['_RUNWAYREQUEST']._serialized_end=178
  _globals['_GATEREQUEST']._serialized_start=180
  _globals['_GATEREQUEST']._serialized_end=232
  _globals['_ASSIGNAIRCRAFTREQUEST']._serialized_start=234
  _globals['_ASSIGNAIRCRAFTREQUEST']._serialized_end=326
  _globals['_EMPTY']._serialized_start=328
  _globals['_EMPTY']._serialized_end=335
  _globals['_RESPONSE']._serialized_start=337
  _globals['_RESPONSE']._serialized_end=380
  _globals['_AIRTRAFFICCONTROL']._serialized_start=383
  _globals['_AIRTRAFFICCONTROL']._serialized_end=772
# @@protoc_insertion_point(module_scope)
